# Copyright (C) 2025 Marc Nieper-Wißkirchen

# Author: Marc Nieper-Wißkirchen

# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

theme: jekyll-theme-primer

domain: www.eggscheme.org
url: https://www.eggscheme.org

github:
  private: false
  license:
    name: "CC BY-ND 4.0"
  source:
    branch: "main"
    path: "/"
  repository_url: "https://github.com/EggScheme/eggscheme.github.io"

title: Egg Scheme
email: bug@eggscheme.org
description: Egg Scheme is an implementation of the Scheme programming language.
repository: EggScheme/EggScheme
